language: python
python: 3.6
#     - 3.4
#     - 3.5
#     - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
      script:
        - py.test /tests/avocato/
    - python: 3.7
      dist: xenial
      sudo: required
      install:
        - pip install -r requirements/django.txt
      script:
        - py.test /tests/vendors/test_django.py

install: 
    - pip install -r requirements/test.txt
before_script:
    - flake8 .
# script:
#     - py.test --cov=./
# after_success:
#   - codecov
branches:
  only:
    - master