language: python
python: 3.6
matrix:
  include:
    - python: 3.7
      env: TEST_SUITE=coverage
      dist: xenial
      sudo: required
      script:
        - pip install -r requirements/test.txt
        - pip install -r requirements/django.txt
        - pip install -r requirements/peewee.txt
        - py.test --cov=./
      after_success:
        - codecov
    - python: 3.7
      env: TEST_SUITE=avocato
      dist: xenial
      sudo: required
      script:
        - pip install -r requirements/test.txt
        - py.test tests/avocato/
    - python: 3.7
      env: TEST_SUITE=django
      dist: xenial
      sudo: required
      install:
        - pip install -r requirements/test.txt
        - pip install -r requirements/django.txt
      script:
        - py.test tests/vendors/test_django.py
    - python: 3.7
      env: TEST_SUITE=peewee
      dist: xenial
      sudo: required
      install:
        - pip install -r requirements/test.txt
        - pip install -r requirements/peewee.txt
      script:
        - py.test tests/vendors/test_peewee.py
    - python: 3.6
      env: TEST_SUITE=avocato
      script:
        - pip install -r requirements/test.txt
        - py.test tests/avocato/
    - python: 3.6
      env: TEST_SUITE=django
      install:
        - pip install -r requirements/test.txt
        - pip install -r requirements/django.txt
      script:
        - py.test tests/vendors/test_django.py
    - python: 3.6
      env: TEST_SUITE=peewee
      install:
        - pip install -r requirements/test.txt
        - pip install -r requirements/peewee.txt
      script:
        - py.test tests/vendors/test_peewee.py
    - python: 3.5
      env: TEST_SUITE=avocato
      script:
        - pip install -r requirements/test.txt
        - py.test tests/avocato/
    - python: 3.5
      env: TEST_SUITE=django
      install:
        - pip install -r requirements/test.txt
        - pip install -r requirements/django.txt
      script:
        - py.test tests/vendors/test_django.py
    - python: 3.5
      env: TEST_SUITE=peewee
      install:
        - pip install -r requirements/test.txt
        - pip install -r requirements/peewee.txt
      script:
        - py.test tests/vendors/test_peewee.py

install: 
    - pip install -r requirements/test.txt
before_script:
    - flake8 .
branches:
  only:
    - master
